support params: paths, ignore_paths, like git
samcontesse/gitlab-merge-request-resource pull request #19
Opened 2019-06-24 07:23 UTC by mgsolid

https://github.com/samcontesse/gitlab-merge-request-resource/issues/16

sample: 

```yaml
resources:
- name: repo-mr
  type: merge-request
  source:
    uri: https://gitlab.eng.company.com/yangye/testing.git
    private_token:
    paths: ["testing/subproject2"]
    # ignore_paths: ["testing/subproject1"]

```

2022-01-12 22:11 UTC, alv-lop commented
@samcontesse Are there any plans on bringing the changes of this PR over?

2022-01-13 07:44 UTC, samcontesse requested changes

2022-01-13 07:45 UTC, samcontesse commented
> @samcontesse Are there any plans on bringing the changes of this PR over?

I did a review a long time ago and forgot to submit it. Let's wait for the author to address them.

2022-02-13 19:59 UTC, samcontesse commented
Closed by #57

2022-02-13 19:59 UTC, closed without merging